import os
import subprocess
from pathlib import Path
from typing import List, Optional, Tuple
from .component import Component
from .generator import HTMLGenerator


class CloudflareWorkerGenerator:
    def __init__(self):
        self.html_generator = HTMLGenerator()
    
    def generate_worker_code(self, components: List[Component], title: str = 'pyHTML Page', head_config: Optional[dict] = None) -> str:
        """生成Cloudflare Worker代码"""
        html_content = self.html_generator.generate_html(components, title, head_config)
        
        worker_code = f"""
export default {{
  async fetch(request, env, ctx) {{
    // 生成HTML响应
    return new Response(`{html_content.replace('`', '\\`')}`, {{
      headers: {{
        'Content-Type': 'text/html; charset=utf-8'
      }}
    }})
  }}
}}
"""
        
        return worker_code
    
    def save_worker(self, components: List[Component], output_path: str, title: str = 'pyHTML Page', head_config: Optional[dict] = None) -> str:
        """保存Cloudflare Worker代码到文件"""
        worker_code = self.generate_worker_code(components, title, head_config)
        output_file = Path(output_path)
        try:
            output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(worker_code)
            return str(output_file)
        except PermissionError:
            raise PermissionError(f'没有权限写入文件: {output_file}')
        except Exception as e:
            raise Exception(f'保存文件失败: {str(e)}')
    
    def create_worker_project(self, project_dir: str, components: List[Component], title: str = 'pyHTML Page', head_config: Optional[dict] = None, worker_name: str = None, custom_domain: str = None) -> str:
        """创建完整的Cloudflare Worker项目结构"""
        project_path = Path(project_dir)
        project_path.mkdir(parents=True, exist_ok=True)
        
        # 创建src目录
        src_path = project_path / 'src'
        src_path.mkdir(exist_ok=True)
        
        # 生成worker代码
        worker_code = self.generate_worker_code(components, title, head_config)
        worker_file = src_path / 'index.js'
        with open(worker_file, 'w', encoding='utf-8') as f:
            f.write(worker_code)
        
        # 从head_config继承配置或使用默认值
        project_name = worker_name or title or 'pyhtml-cloudflare-worker'
        project_name = project_name.lower().replace(' ', '-')
        # 过滤掉非字母数字和破折号的字符
        import re
        project_name = re.sub(r'[^a-z0-9-]', '', project_name)
        # 确保项目名不为空
        if not project_name:
            project_name = 'pyhtml-cloudflare-worker'
        
        # 创建package.json
        package_json = {
            "name": project_name,
            "version": "1.0.0",
            "description": head_config.get('description', 'Cloudflare Worker generated by pyHTML') if head_config else 'Cloudflare Worker generated by pyHTML',
            "main": "src/index.js",
            "scripts": {
                "dev": "npx wrangler dev",
                "deploy": "npx wrangler deploy"
            },
            "dependencies": {},
            "devDependencies": {
                "wrangler": "^3.0.0"
            }
        }
        import json
        with open(project_path / 'package.json', 'w', encoding='utf-8') as f:
            json.dump(package_json, f, indent=2)
        
        # 创建wrangler.jsonc
        wrangler_config = {
            "name": project_name,
            "main": "src/index.js",
            "compatibility_date": "2023-01-01",
            "workers_dev": True
        }
        
        # 添加自定义域名配置
        if custom_domain:
            wrangler_config["routes"] = [
                {
                    "pattern": custom_domain,
                    "custom_domain": True
                }
            ]
        
        with open(project_path / 'wrangler.jsonc', 'w', encoding='utf-8') as f:
            f.write('// wrangler.jsonc\n')
            json.dump(wrangler_config, f, indent=2)
        
        # 创建.gitignore
        gitignore_content = """
# Dependencies
node_modules/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Build files
dist/
build/

# Logs
logs
*.log

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
"""
        with open(project_path / '.gitignore', 'w', encoding='utf-8') as f:
            f.write(gitignore_content)
        
        # 保存.pyhtml文件
        import json
        project_data = {
            "name": project_name,
            "title": title,
            "components": [component.to_dict() for component in components],
            "head_config": head_config or {
                "lang": "zh-CN",
                "meta_tags": [
                    {"name": "charset", "content": "UTF-8"},
                    {"name": "viewport", "content": "width=device-width, initial-scale=1.0"}
                ],
                "links": [],
                "scripts": []
            }
        }
        with open(project_path / f"{project_name}.pyhtml", 'w', encoding='utf-8') as f:
            json.dump(project_data, f, ensure_ascii=False, indent=2)
        
        return str(project_path)
    
    def _check_node_available(self) -> bool:
        """检查Node.js是否可用"""
        try:      
            # 尝试运行node --version
            result = subprocess.run(
                ['node', '--version'],
                capture_output=True,
                text=True,
                encoding='utf-8',
                shell=True
            )
            
            if result.returncode == 0:
                print('Node.js可用!')
                return True
            else:
                print('Node.js不可用，退出码不为0')
                return False
        except FileNotFoundError as e:
            print(f'错误: 系统找不到node命令: {str(e)}')
            return False
        except Exception as e:
            print(f'检查Node.js时发生错误: {str(e)}')
            import traceback
            traceback.print_exc()
            return False
    
    def _check_npm_available(self) -> bool:
        """检查npm是否可用"""
        try:      
            # 尝试不同的方式运行npm
            result = subprocess.run(
                ['npm', '--version'],
                capture_output=True,
                text=True,
                encoding='utf-8',  # 明确指定编码为UTF-8
                shell=True  # 使用shell=True可能会解决路径问题
            )
            
            if result.returncode == 0:
                print('npm可用!')
                return True
            else:
                print('npm不可用，退出码不为0')
                return False
        except FileNotFoundError as e:
            print(f'错误: 系统找不到npm命令: {str(e)}')
            return False
        except Exception as e:
            print(f'检查npm时发生错误: {str(e)}')
            import traceback
            traceback.print_exc()
            return False
    
    def _install_nodejs(self, log_callback=None) -> bool:
        """自动安装Node.js"""
        try:
            import os
            import tempfile
            import requests
            import zipfile
            import shutil
            
            log_message = '开始自动安装Node.js...'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            
            # 下载Node.js安装包
            # 这里使用最新的LTS版本
            nodejs_url = 'https://nodejs.org/dist/v20.11.0/node-v20.11.0-win-x64.zip'
            log_message = f'正在下载Node.js: {nodejs_url}'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            
            # 创建临时目录
            with tempfile.TemporaryDirectory() as temp_dir:
                zip_path = os.path.join(temp_dir, 'nodejs.zip')
                
                # 下载文件
                response = requests.get(nodejs_url, stream=True)
                total_size = int(response.headers.get('content-length', 0))
                downloaded_size = 0
                
                with open(zip_path, 'wb') as f:
                    for chunk in response.iter_content(chunk_size=8192):
                        if chunk:
                            f.write(chunk)
                            downloaded_size += len(chunk)
                            if total_size > 0:
                                progress = (downloaded_size / total_size) * 100
                                if log_callback:
                                    log_callback(f'下载进度: {progress:.1f}%')
                
                # 解压到临时目录
                log_message = '正在解压Node.js...'
                print(log_message)
                if log_callback:
                    log_callback(log_message)
                
                with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                    zip_ref.extractall(temp_dir)
                
                # 找到解压后的目录
                nodejs_dir = os.path.join(temp_dir, os.listdir(temp_dir)[0])
                
                # 安装到Program Files
                install_dir = os.path.join(os.environ.get('ProgramFiles', r'C:\Program Files'), 'nodejs')
                log_message = f'正在安装到: {install_dir}'
                print(log_message)
                if log_callback:
                    log_callback(log_message)
                
                # 清理旧安装
                if os.path.exists(install_dir):
                    shutil.rmtree(install_dir)
                
                # 复制文件
                shutil.copytree(nodejs_dir, install_dir)
                
                # 添加到环境变量
                path = os.environ.get('PATH', '')
                if install_dir not in path:
                    os.environ['PATH'] = f'{install_dir};{path}'
                    # 永久添加到环境变量
                    import winreg
                    key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Environment', 0, winreg.KEY_SET_VALUE)
                    winreg.SetValueEx(key, 'PATH', 0, winreg.REG_EXPAND_SZ, f'{install_dir};{path}')
                    winreg.CloseKey(key)
                    log_message = '已添加Node.js到环境变量'
                    print(log_message)
                    if log_callback:
                        log_callback(log_message)
                
            log_message = 'Node.js安装成功!'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            return True
        except Exception as e:
            error_message = f'安装Node.js时发生错误: {str(e)}'
            print(error_message)
            if log_callback:
                log_callback(error_message)
            import traceback
            traceback.print_exc()
            return False
    
    def install_dependencies(self, project_dir: str, log_callback=None) -> bool:
        """安装项目依赖"""
        # 检查Node.js是否可用
        if not self._check_node_available():
            # 尝试自动安装Node.js
            if not self._install_nodejs(log_callback):
                return False
        
        # 检查npm是否可用
        if not self._check_npm_available():
            return False
        
        try:
            log_message = '正在安装项目依赖...'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            
            # 实时输出安装过程
            import sys
            process = subprocess.Popen(
                ['npm', 'install'],
                cwd=project_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding='utf-8',
                shell=True
            )
            
            while True:
                line = process.stdout.readline()
                if not line:
                    break
                line = line.strip()
                print(line)
                if log_callback:
                    log_callback(line)
                sys.stdout.flush()
            
            returncode = process.wait()
            
            if returncode == 0:
                success_message = '依赖安装成功!'
                print(success_message)
                if log_callback:
                    log_callback(success_message)
                return True
            else:
                error_message = '安装依赖失败!'
                print(error_message)
                if log_callback:
                    log_callback(error_message)
                return False
        except Exception as e:
            error_message = f'安装依赖时发生错误: {str(e)}'
            print(error_message)
            if log_callback:
                log_callback(error_message)
            import traceback
            traceback.print_exc()
            return False
    
    def deploy_worker(self, project_dir: str, api_token: str = None, custom_domain: str = None, log_callback=None) -> Tuple[bool, Optional[str]]:
        """部署Cloudflare Worker"""
        # 检查Node.js是否可用
        if not self._check_node_available():
            # 尝试自动安装Node.js
            if not self._install_nodejs(log_callback):
                return False, None
        
        # 检查npm是否可用
        if not self._check_npm_available():
            return False, None       
        try:
            # 检查CLOUDFLARE_API_TOKEN
            import os
            
            # 优先使用传入的api_token参数
            if api_token:
                log_message = '使用传入的API token'
                print(log_message)
                if log_callback:
                    log_callback(log_message)
            else:
                # 尝试从环境变量获取
                api_token = os.environ.get('CLOUDFLARE_API_TOKEN')
                log_message = f'CLOUDFLARE_API_TOKEN环境变量值: {api_token if api_token else "未设置"}'
                print(log_message)
                if log_callback:
                    log_callback(log_message)
            
            if not api_token:
                error_messages = [
                    '错误: 未设置CLOUDFLARE_API_TOKEN',
                    '请通过以下方式之一设置API token:',
                    '1. 设置CLOUDFLARE_API_TOKEN环境变量',
                    '2. 在部署时传入API token参数',
                    '3. 手动部署: 进入项目目录并运行 npm run deploy',
                    '\n获取API token的步骤:',
                    '1. 访问 https://developers.cloudflare.com/fundamentals/api/get-started/create-token/',
                    '2. 创建一个具有Workers权限的API token'
                ]
                for message in error_messages:
                    print(message)
                    if log_callback:
                        log_callback(message)
                return False, None
            else:
                log_message = 'API token已设置'
                print(log_message)
                if log_callback:
                    log_callback(log_message)
            
            # 设置环境变量，以便wrangler可以使用
            os.environ['CLOUDFLARE_API_TOKEN'] = api_token
            
            # 先安装依赖
            log_message = '正在安装wrangler依赖...'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            if not self.install_dependencies(project_dir, log_callback):
                return False, None
            
            # 部署worker
            log_message = '正在部署到Cloudflare...'
            print(log_message)
            if log_callback:
                log_callback(log_message)
            
            # 实时输出部署过程
            import sys
            process = subprocess.Popen(
                ['npx', 'wrangler', 'deploy'],
                cwd=project_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding='utf-8',
                shell=True
            )
            
            stdout = []
            while True:
                line = process.stdout.readline()
                if not line:
                    break
                line = line.strip()
                print(line)
                if log_callback:
                    log_callback(line)
                sys.stdout.flush()
                stdout.append(line)
            
            stdout = ''.join(stdout)
            returncode = process.wait()
            
            if returncode == 0:
                success_message = '部署成功!'
                print(success_message)
                if log_callback:
                    log_callback(success_message)
                
                # 提取部署的URL
                deployed_url = None
                
                # 如果有自定义域名，优先使用自定义域名
                if custom_domain:
                    deployed_url = custom_domain
                else:
                    # 从输出中提取workers.dev域名
                    import re
                    match = re.search(r'https://[a-zA-Z0-9.-]+\.workers\.dev', stdout)
                    if match:
                        deployed_url = match.group(0)
                
                url_message = f'部署的URL: {deployed_url}'
                print(url_message)
                if log_callback:
                    log_callback(url_message)
                return True, deployed_url
            else:
                error_message = '部署失败:'
                print(error_message)
                if log_callback:
                    log_callback(error_message)
                
                # 检查是否是域名不存在的错误
                if 'The zone' in stdout and 'does not exist on your account' in stdout:
                    domain_error_message = '错误: 您指定的域名不存在于您的Cloudflare账户中。请更换一个可用的域名。'
                    print(domain_error_message)
                    if log_callback:
                        log_callback(domain_error_message)
                
                return False, None
        except FileNotFoundError as e:
            error_message = f'错误: 系统找不到指定的文件: {str(e)}'
            print(error_message)
            if log_callback:
                log_callback(error_message)
            error_message = '请确保Node.js已安装并添加到环境变量中。'
            print(error_message)
            if log_callback:
                log_callback(error_message)
            return False, None
        except Exception as e:
            error_message = f'部署过程中发生错误: {str(e)}'
            print(error_message)
            if log_callback:
                log_callback(error_message)
            import traceback
            traceback.print_exc()
            return False, None