import os
import subprocess
from pathlib import Path
from typing import List, Optional
from .component import Component
from .generator import HTMLGenerator


class CloudflareWorkerGenerator:
    def __init__(self):
        self.html_generator = HTMLGenerator()
    
    def generate_worker_code(self, components: List[Component], title: str = 'pyHTML Page', head_config: Optional[dict] = None) -> str:
        """生成Cloudflare Worker代码"""
        html_content = self.html_generator.generate_html(components, title, head_config)
        
        worker_code = f"""
export default {{
  async fetch(request, env, ctx) {{
    // 生成HTML响应
    return new Response(`{html_content.replace('`', '\\`')}`, {{
      headers: {{
        'Content-Type': 'text/html; charset=utf-8'
      }}
    }})
  }}
}}
"""
        
        return worker_code
    
    def save_worker(self, components: List[Component], output_path: str, title: str = 'pyHTML Page', head_config: Optional[dict] = None) -> str:
        """保存Cloudflare Worker代码到文件"""
        worker_code = self.generate_worker_code(components, title, head_config)
        output_file = Path(output_path)
        try:
            output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(worker_code)
            return str(output_file)
        except PermissionError:
            raise PermissionError(f'没有权限写入文件: {output_file}')
        except Exception as e:
            raise Exception(f'保存文件失败: {str(e)}')
    
    def create_worker_project(self, project_dir: str, components: List[Component], title: str = 'pyHTML Page', head_config: Optional[dict] = None, worker_name: str = None, custom_domain: str = None) -> str:
        """创建完整的Cloudflare Worker项目结构"""
        project_path = Path(project_dir)
        project_path.mkdir(parents=True, exist_ok=True)
        
        # 创建src目录
        src_path = project_path / 'src'
        src_path.mkdir(exist_ok=True)
        
        # 生成worker代码
        worker_code = self.generate_worker_code(components, title, head_config)
        worker_file = src_path / 'index.js'
        with open(worker_file, 'w', encoding='utf-8') as f:
            f.write(worker_code)
        
        # 从head_config继承配置或使用默认值
        project_name = worker_name or title or 'pyhtml-cloudflare-worker'
        project_name = project_name.lower().replace(' ', '-')
        
        # 创建package.json
        package_json = {
            "name": project_name,
            "version": "1.0.0",
            "description": head_config.get('description', 'Cloudflare Worker generated by pyHTML') if head_config else 'Cloudflare Worker generated by pyHTML',
            "main": "src/index.js",
            "scripts": {
                "dev": "npx wrangler dev",
                "deploy": "npx wrangler deploy"
            },
            "dependencies": {},
            "devDependencies": {
                "wrangler": "^3.0.0"
            }
        }
        import json
        with open(project_path / 'package.json', 'w', encoding='utf-8') as f:
            json.dump(package_json, f, indent=2)
        
        # 创建wrangler.jsonc
        wrangler_config = {
            "name": project_name,
            "main": "src/index.js",
            "compatibility_date": "2023-01-01",
            "workers_dev": True
        }
        
        # 添加自定义域名配置
        if custom_domain:
            wrangler_config["routes"] = [
                {
                    "pattern": custom_domain,
                    "custom_domain": True
                }
            ]
        
        with open(project_path / 'wrangler.jsonc', 'w', encoding='utf-8') as f:
            f.write('// wrangler.jsonc\n')
            json.dump(wrangler_config, f, indent=2)
        
        # 创建.gitignore
        gitignore_content = """
# Dependencies
node_modules/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Build files
dist/
build/

# Logs
logs
*.log

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
"""
        with open(project_path / '.gitignore', 'w', encoding='utf-8') as f:
            f.write(gitignore_content)
        
        return str(project_path)
    
    def _check_npm_available(self) -> bool:
        """检查npm是否可用"""
        try:
            # 尝试使用完整路径
            import os
            # 检查环境变量PATH
            path = os.environ.get('PATH', '')
            print(f'当前PATH环境变量: {path}')
            
            # 尝试不同的方式运行npm
            print('尝试运行npm --version...')
            result = subprocess.run(
                ['npm', '--version'],
                capture_output=True,
                text=True,
                encoding='utf-8',  # 明确指定编码为UTF-8
                shell=True  # 使用shell=True可能会解决路径问题
            )
            print(f'npm --version 退出码: {result.returncode}')
            print(f'npm --version 输出: {result.stdout}')
            print(f'npm --version 错误: {result.stderr}')
            
            if result.returncode == 0:
                print('npm可用!')
                return True
            else:
                print('npm不可用，退出码不为0')
                return False
        except FileNotFoundError as e:
            print(f'错误: 系统找不到npm命令: {str(e)}')
            return False
        except Exception as e:
            print(f'检查npm时发生错误: {str(e)}')
            import traceback
            traceback.print_exc()
            return False
    
    def install_dependencies(self, project_dir: str) -> bool:
        """安装项目依赖"""
        if not self._check_npm_available():
            return False
        
        try:
            print('正在安装依赖...')
            result = subprocess.run(
                ['npm', 'install'],
                cwd=project_dir,
                capture_output=True,
                text=True,
                encoding='utf-8',  # 明确指定编码为UTF-8
                shell=True  # 使用shell=True
            )
            
            print(f'npm install 退出码: {result.returncode}')
            print(f'npm install 输出: {result.stdout}')
            print(f'npm install 错误: {result.stderr}')
            
            if result.returncode == 0:
                print('依赖安装成功!')
                return True
            else:
                print(f'安装依赖失败: {result.stderr}')
                return False
        except Exception as e:
            print(f'安装依赖时发生错误: {str(e)}')
            import traceback
            traceback.print_exc()
            return False
    
    def deploy_worker(self, project_dir: str, api_token: str = None) -> bool:
        """部署Cloudflare Worker"""
        if not self._check_npm_available():
            return False
        
        try:
            # 检查CLOUDFLARE_API_TOKEN
            import os
            print('=== 环境变量检查 ===')
            print(f'当前工作目录: {os.getcwd()}')
            
            # 优先使用传入的api_token参数
            if api_token:
                print('使用传入的API token')
            else:
                # 尝试从环境变量获取
                api_token = os.environ.get('CLOUDFLARE_API_TOKEN')
                print(f'CLOUDFLARE_API_TOKEN环境变量值: {api_token if api_token else "未设置"}')
            
            if not api_token:
                print('错误: 未设置CLOUDFLARE_API_TOKEN')
                print('请通过以下方式之一设置API token:')
                print('1. 设置CLOUDFLARE_API_TOKEN环境变量')
                print('2. 在部署时传入API token参数')
                print('3. 手动部署: 进入项目目录并运行 npm run deploy')
                print('\n获取API token的步骤:')
                print('1. 访问 https://developers.cloudflare.com/fundamentals/api/get-started/create-token/')
                print('2. 创建一个具有Workers权限的API token')
                return False
            else:
                print('API token已设置')
            
            # 设置环境变量，以便wrangler可以使用
            os.environ['CLOUDFLARE_API_TOKEN'] = api_token
            
            # 先安装依赖
            print('正在安装依赖...')
            if not self.install_dependencies(project_dir):
                return False
            
            # 部署worker
            print('正在部署到Cloudflare...')
            result = subprocess.run(
                ['npx', 'wrangler', 'deploy'],
                cwd=project_dir,
                capture_output=True,
                text=True,
                encoding='utf-8',  # 明确指定编码为UTF-8
                shell=True  # 使用shell=True
            )
            
            print(f'npx wrangler deploy 退出码: {result.returncode}')
            print(f'npx wrangler deploy 输出: {result.stdout}')
            print(f'npx wrangler deploy 错误: {result.stderr}')
            
            if result.returncode == 0:
                print('部署成功!')
                print(result.stdout)
                return True
            else:
                print('部署失败:')
                print(result.stderr)
                return False
        except FileNotFoundError as e:
            print(f'错误: 系统找不到指定的文件: {str(e)}')
            print('请确保Node.js已安装并添加到环境变量中。')
            return False
        except Exception as e:
            print(f'部署过程中发生错误: {str(e)}')
            import traceback
            traceback.print_exc()
            return False